### ISSUE TITLE
BPM off / tempo deviating

### ISSUE THREAD

**Issue by antonhornquist** [antonhornquist/step#5]
something to look into.

from carvingcode on lines:

"After 1 to 1.5 measures, it is noticeable. This is with or without swing."

"I tested against a metronome app and another norns app at 60 BPM."

"May be happening in rounding error in update_swing(). Shouldn’t swing value only be applied to the odd?"

**Comment by simonvanderveldt** [comment]
Just compared at 62BPM vs 62BPM on software MIDI sequence/synth and those drifted, sequencer was a bit faster.
Not sure I'm hearing a lot of variation though. Could it be reverb that makes it sound like that? With (system) reverb off it seems pretty stable for me.

**Comment by antonhornquist** [comment]
i could recreate this yesterday. i initially thought tempo was deviating in that it _changed_ after some measure, but can conclude that the tempo appear to stay constant but it is not the tempo that is displayed in the UI.

I tested by running Renoise @ 60 BPM and compared to Step @ 60 BPM, and as reported, immediately (after a bar or so) the difference can be heard. Lowering tempo in Renoise to 58 BPM would sync Renoise and Step up better but after some time the difference is heard still.

I'll investigate this further.

Thanks @carvingcode for finding this.

**Comment by antonhornquist** [comment]
i found a bug in `tick()` today that caused this. I will have a fix ready for this in next version of Step.

**Comment by antonhornquist** [comment]
fix in 2ca2e71015512b90ce25e2c29f888ed7c0a543c7
